### ISSUE TITLE
"Illegal instruction" on old CPU (i5-650)

### ISSUE THREAD

**Issue by vkcz** [shssoichiro/oxipng#289] opened 2020-08-18 19:03 UTC
I was able to build/install `oxipng` (`cargo install oxipng`) just fine, and `oxipng` with no arguments or `oxipng --help` work fine, but trying to actually use `oxipng` to optimize a PNG gives
```
Processing: <redacted>.png
    2048x2048 pixels, PNG format
    4x8 bits/pixel, RGBA
    IDAT size = 994099 bytes
    File size = 994156 bytes
Illegal instruction
```
My default toolchain is `stable-x86_64-pc-windows-msvc`. More information at the duplicate of this (https://github.com/rust-lang/rust/issues/75612)

**Comment by andrews05** [comment] 2023-05-01 18:12
@vkcz I’m guessing this was caused by cf-zlib, which has since been removed. Can you check if this is still happening on the latest release?

**Comment by andrews05** [comment] 2023-07-10 01:12
Closing as presumed fixed. Feel to reopen if necessary.

**Closed by andrews05** 2023-07-10 01:12 UTC
Labels: T-Bug, I-High
