### ISSUE TITLE
Add lossy support via specifiable max bit depth and max pallet size

### ISSUE THREAD

**Issue by AndreVallestero** [shssoichiro/oxipng#421] opened 2021-10-15 13:16 UTC

**Comment by ace-dent** [comment] 2023-10-08 12:06
I would suggest this feature is well catered for with dedicated tools, like [pngquant](https://pngquant.org), [imageworsener](https://entropymine.com/imageworsener/), etc.

@shssoichiro perhaps a top-level decision is needed: to what extent will lossy reductions be provided in `oxipng` ...?

**Comment by andrews05** [comment] 2023-10-08 20:57
I'll close this as a duplicate of #76. I do agree pairing with pngquant would be best for this.

We also have `--scale16` now which is a lossy depth reduction specifically for 16-bit.

**Closed by andrews05** 2023-10-08 20:57 UTC
Labels: T-Feature, T-Compression
