### ISSUE TITLE
Chooses 2-bit grayscale over 1-bit indexed

### ISSUE THREAD

**Issue by Pr0methean** [shssoichiro/oxipng#515] opened 2023-05-31 16:32 UTC
When I optimize a 4096x4096, 4x8-bit RGBA image where each pixel is either transparent or opaque black, it is output as 8-bit grayscale, even though it could actually be 1-bit indexed (as it is when the opaque pixels are the same non-gray color). Likewise when the opaque pixels are 0xaaaaaa, it is output as 2-bit grayscale, and 0x515151, 8-bit grayscale. Only white seems to avoid this issue.

**Comment by Pr0methean** [comment] 2023-05-31 16:49
NB: I experienced this with 8.0.0, and it looks to me like this may already be fixed in master; if so, when can we expect a release?

**Comment by Pr0methean** [comment] 2023-05-31 19:35
Update: as of 86fccf0 this is fixed for all but the case of 0x515151, which is still 2-bit grayscale.

**Comment by andrews05** [comment] 2023-05-31 21:34
Regarding the 2-bit grayscale: Currently to keep things simple and avoid additional reduction attempts, it won't try low-depth indexed if it can do low-depth grayscale - it makes an assumption here that the low-depth grayscale will be better (which most of the time it is). Oxipng has extensive reductions, but not exhaustive.
The black preferring 1-bit indexed sounds odd though, could you post the image?

**Comment by ace-dent** [comment] 2023-06-01 14:17
@andrews05 I've seen this before and it relates to the palette optimization / `0` filter interaction I mentioned. 
The savings with setting edge color to palette entry `0` can outweigh the overhead of storing a palette. IMO it is worth checking indexed image in addition to grayscale (perhaps just for higher optimization levels?). I have a large collection of 1 bit images [here](https://github.com/ace-dent/8x8.me/tree/main/previews).

**Comment by Pr0methean** [comment] 2023-06-01 20:28
Here's the image:
![black_stained_glass_pane_top](https://github.com/shssoichiro/oxipng/assets/4961925/6ea31d4f-932f-45aa-a363-b63fb8a4c7d0)

**Comment by Pr0methean** [comment] 2023-06-01 20:31
As a workaround, I'm testing writing the original PNG in grayscale or indexed mode in cases where I can know all the colors based on how the image was generated.

**Comment by andrews05** [comment] 2023-06-01 21:01
Oh I see, it's caused by the tRNS chunk which is set to a grey level of 1. If it was 255 (white) then it would successfully reduce to 1-bit, but oxipng doesn't currently perform this kind of optimisation of tRNS values. Were there other tools you tried that successfully reduced this?

**Comment by Pr0methean** [comment] 2023-06-01 21:13
No; I've been doing everything in Rust so that I can pack the PNGs into a zip file in memory, and thus avoid blocking on disk operations until all the CPU work is done, and therefore only need Rayon and not Tokio.

**Comment by andrews05** [comment] 2023-06-01 21:56
Sure, I ask because I think this would be a very, um, "advanced" type of transformation which would be tricky to implement. I tried a few other tools, none of which gave 1-bit grayscale:
ect: 1-bit indexed
optipng: 1-bit indexed
pngoptimizer: 8-bit grayscale
zopflipng: 1-bit indexed

**Comment by andrews05** [comment] 2023-06-01 22:13
@ace-dent I think in this case the issue is more that the indexed could have been 1-bit while the grayscale required 2-bit.

**Comment by ace-dent** [comment] 2023-06-04 13:14
@Pr0methean @andrews05 
-- I ran the image (for fun!) through my script 'pngslim' and got to 6,249 bytes, 1 bit paletted image. I think indexed is optimal here. Let me know if you find a better solution. :-)

![242719095-6ea31d4f-932f-45aa-a363-b63fb8a4c7d0](https://github.com/shssoichiro/oxipng/assets/473224/1164cb1e-64b6-49ac-ac76-6e56f7d1191b)

**Comment by andrews05** [comment] 2023-06-05 03:07
@ace-dent Best I can do with oxipng is 6,284, 1-bit indexed. After manually turning it into 1-bit grayscale, I get 6,268. Here's the grayscale version:
![testg](https://github.com/shssoichiro/oxipng/assets/4584038/f76fc43a-be29-4c35-95ce-e59f4b1aabf5)

**Comment by andrews05** [comment] 2023-07-10 01:08
#520 was recently merged which fixes the situation with the black and transparent image. If the input image is RGBA or GrayAlpha (i.e. not already using a tRNS chunk), it will now pick a better value for the tRNS chunk that allows it to reduce to 1-bit.

**Comment by ace-dent** [comment] 2023-10-08 12:10
@andrews05 - fixed now?

**Comment by TPS** [comment] 2023-10-08 13:13
> #520 was recently merged which fixes the situation with the black and transparent image. If the input image is RGBA or GrayAlpha (i.e. not already using a tRNS chunk), it will now pick a better value for the tRNS chunk that allows it to reduce to 1-bit.

@ace-dent Seems so, per this, but did you test your OP files from a recent binary?

**Comment by andrews05** [comment] 2023-10-08 20:26
The original issue "Chooses 2-bit grayscale over 1-bit indexed" still remains.

**Closed** 2024-03-11 04:38 UTC
Labels: T-Compression
