### ISSUE TITLE
x86-64 binary failing on my Xeon CPU

### ISSUE THREAD

**Issue by iamtherobin** [shssoichiro/oxipng#423] opened 2021-11-11 23:39 UTC
I have an old LGA1366 Intel platform using X58 with Windows 7 installed.

Previous I was using a Core i7 950 (4C/8T 45nm Nahalem) CPU. oxipng v5 x86-64 worked no problem. (CPU details: https://ark.intel.com/content/www/us/en/ark/products/37150/intel-core-i7950-processor-8m-cache-3-06-ghz-4-80-gts-intel-qpi.html).
oxipng v5 x86-64 worked no problem.

I recently upgraded to Xeon W3680 (6C/12T 32nm Westmere) CPU. (CPU details: https://ark.intel.com/content/www/us/en/ark/products/47917/intel-xeon-processor-w3680-12m-cache-3-33-ghz-6-40-gts-intel-qpi.html)
Since then, any x86-64 build will produce an exception error immediately at runtime. Only i686 builds are working. I have no encountered any issues with any other software since switching.

Here is the details from the windows crash report (v5 x86-64 build):
------------------------------------------------------
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	oxipng.exe
  Application Version:	0.0.0.0
  Application Timestamp:	60ebc0aa
  Fault Module Name:	oxipng.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	60ebc0aa
  Exception Code:	c000001d
  Exception Offset:	000000000012c8de
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	4105
  Additional Information 1:	6c0b
  Additional Information 2:	6c0b4b254207678ccceec59af3dba05e
  Additional Information 3:	3fa9
  Additional Information 4:	3fa9f9239419119caa53023a1831326c
------------------------------------------------------

Searching exception code "c000001d" doesn't produce any helpful results. I did try cleaning out all my MSVC runtimes and reinstalling them. That didn't change anything.

**Comment by andrews05** [comment] 2023-05-02 06:11
I believe this is a duplicate of #289. As I mentioned there, this should be resolved now as cloudflare-zlib has been removed.

**Comment by andrews05** [comment] 2023-07-10 01:12
Closing as presumed fixed. Feel to reopen if necessary.

**Closed by andrews05** 2023-07-10 01:12 UTC

**Comment by iamtherobin** [comment] 2023-07-23 02:05
Just confirming v8.0.0 x86-64 build us working for me now.
